[package]
name = "nu_plugin_port_list"
license = "MIT"
authors = ["Motalleb Fallahnezhad <fmotalleb@gmail.com>"]
keywords = ["nushell", "network", "plugin"]
homepage = "https://github.com/FMotalleb/nu_plugin_port_list"
repository = "https://github.com/FMotalleb/nu_plugin_port_list"
description = "A nushell plugin to list all active connections"
version = "1.1.1"
edition = "2021"
readme = "README.md"

[dependencies]
nu-plugin = "0.86.0"
nu-protocol = { version = "0.86.0", features = ["plugin"] }
netstat2 = "0.9.0"
sysinfo = "0.29.10"
